package ruler

import "net/http"

type Handler interface {
	ListRules(http.ResponseWriter, *http.Request)
	GetRuleByID(http.ResponseWriter, *http.Request)
	CreateRule(http.ResponseWriter, *http.Request)
	UpdateRuleByID(http.ResponseWriter, *http.Request)
	DeleteRuleByID(http.ResponseWriter, *http.Request)
	PatchRuleByID(http.ResponseWriter, *http.Request)
	TestRule(http.ResponseWriter, *http.Request)
	PreviewNotificationTemplate(http.ResponseWriter, *http.Request)
	PreviewSOP(http.ResponseWriter, *http.Request)
	FetchPilotManagedMarkdownSOP(http.ResponseWriter, *http.Request)
	ListPilotSOPSources(http.ResponseWriter, *http.Request)
	GetPilotSOPSourceHealth(http.ResponseWriter, *http.Request)
	CreateSOPDocument(http.ResponseWriter, *http.Request)
	CreateSOPDocumentBatch(http.ResponseWriter, *http.Request)
	ListSOPDocuments(http.ResponseWriter, *http.Request)
	GetSOPDocument(http.ResponseWriter, *http.Request)
	FetchSOPDocumentVersion(http.ResponseWriter, *http.Request)
	PreviewSOPDocumentBinding(http.ResponseWriter, *http.Request)
	PreviewAIStrategy(http.ResponseWriter, *http.Request)
	GetLatestAIStrategyHistory(http.ResponseWriter, *http.Request)
	GetAIConfig(http.ResponseWriter, *http.Request)
	UpdateAIConfig(http.ResponseWriter, *http.Request)
	TestAIConfig(http.ResponseWriter, *http.Request)

	GetCodebaseRCAConfig(http.ResponseWriter, *http.Request)
	UpdateCodebaseRCAConfig(http.ResponseWriter, *http.Request)
	ListCodebaseRepos(http.ResponseWriter, *http.Request)
	UpsertCodebaseRepo(http.ResponseWriter, *http.Request)
	DeleteCodebaseRepo(http.ResponseWriter, *http.Request)
	ListCodebaseServiceMaps(http.ResponseWriter, *http.Request)
	UpsertCodebaseServiceMap(http.ResponseWriter, *http.Request)
	DeleteCodebaseServiceMap(http.ResponseWriter, *http.Request)
	ListCodeRCARuns(http.ResponseWriter, *http.Request)
	GetCodeRCARun(http.ResponseWriter, *http.Request)

	GetIncidentReportTemplate(http.ResponseWriter, *http.Request)
	UpdateIncidentReportTemplate(http.ResponseWriter, *http.Request)
	GenerateIncidentReport(http.ResponseWriter, *http.Request)

	ListRunbooks(http.ResponseWriter, *http.Request)
	GetRunbook(http.ResponseWriter, *http.Request)
	CreateRunbook(http.ResponseWriter, *http.Request)
	UpdateRunbook(http.ResponseWriter, *http.Request)
	DeleteRunbook(http.ResponseWriter, *http.Request)
	DraftRunbook(http.ResponseWriter, *http.Request)

	ListDowntimeSchedules(http.ResponseWriter, *http.Request)
	GetDowntimeScheduleByID(http.ResponseWriter, *http.Request)
	CreateDowntimeSchedule(http.ResponseWriter, *http.Request)
	UpdateDowntimeScheduleByID(http.ResponseWriter, *http.Request)
	DeleteDowntimeScheduleByID(http.ResponseWriter, *http.Request)
}
